### ISSUE TITLE
Proposal for auto publish process

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#336]
We want it to be easy to publish versions of Microstates and allow contributors to help publish new versions without requiring NPM credentials. This process will use CircleCI to automatically run jobs on push to `master` and PRs.

The overall process will be this,

1. Create a PR
2. Update CHANGELOG.md and describe your change
3. Update package.json with a release version

When the PR is merged into `master`, if the merge includes a change to the version in package.json then automatically publish the new version to NPM.

This process will use Danger bot to automatically inform contributors of this process by publishing a comment to the PR. The PRs will be blocked until CHANGELOG.md is updated. 

## Todos

- [ ] Move to CircleCI #337 
- [ ] Setup Danger Bot to notify of this process
- [ ] Make PRs blocked if CHANGELOG is not updated
- [ ] Setup publish script for version changes

What else do I need?

**Comment by cowboyd** [comment]
Can we make this release branch specific? I'm thinking of the case, where we have both `1.0` and `2.0` versions released, and we want to release a bug fix to both releases as the `1.1`, and `2.1`

If we could follow this simple tree pattern with our branch/tag -> release, then we should be able to very easily maintain _any_ portion of the tree, not just the latest release.

```
┌─────┐
│1.x.x│
└─┬───┘
  │
  │      ┌─────┐
  ├─────▶│1.0.x│
  │      └──┬──┘
  │         │      ┌─────┐
  │         ├─────▶│1.0.0│
  │         │      └─────┘
  │         │      ┌─────┐
  │         ├─────▶│1.0.1│
  │         │      └─────┘
  │         │
  │         │
  │         │
  │         │
  │         │
  │         │
  │         │
  │         │      ┌─────┐
  ├─────────┼─────▶│1.1.x│
  │         │      └──┬──┘
  │         │         │      ┌─────┐
  │         │         ├─────▶│1.1.0│
  │         │         │      └─────┘
  │         │         │      ┌─────┐
  │         │         ├─────▶│1.1.1│
  │         │         │      └─────┘
  │         │         │
  │         │         │
  │         │         │
  │         │         │
  │         │         │                 ┌─────┐
  ├─────────┼─────────┼────────────────▶│2.x.x│
  │         │         │                 └─┬───┘
  │         │         │                   │
  │         │         │                   │      ┌─────┐
  │         │         │                   ├─────▶│2.0.x│
  │         │         │                   │      └──┬──┘
  │         │         │                   │         │      ┌─────┐
  │         │         │                   │         ├─────▶│2.0.0│
  │         │         │                   │         │      └─────┘
  │         │         │                   │         │      ┌─────┐
  │         │         │                   │         ├─────▶│2.0.1│
  │         │         │                   │         │      └─────┘
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │
  │         │         │                   │         │      ┌─────┐
  │         │         │                   ├─────────┼─────▶│2.1.x│
  │         │         │                   │         │      └──┬──┘
  │         │         │                   │         │         │      ┌─────┐
  │         │         │                   │         │         ├─────▶│2.1.0│
  │         │         │                   │         │         │      └─────┘
  │         │         │                   │         │         │      ┌─────┐
  │         │         │                   │         │         ├─────▶│2.1.1│
  │         │         │                   │         │         │      └─────┘
  │         │         │                   │         │         │
  │         │         │                   │         │         │
  │         │         │                   │         │         │
  ▼         ▼         ▼                   ▼         ▼         ▼
```

We've run into this before maintaining ember addons where someone is using an older version of the addon, because they're using an older version of Ember, so upgrading is not a possibility because they can't upgrade their framework. And because we don't have a way to easily back-patch a release, they're kinda left hanging. 

However, if we had a system like the one outlined above, then not only can we help those people, but the workflow becomes "Just submit a pull request to the `release-1.2.x` branch" which means they're empowered to self-serve.

What about this? 

When you merge a PR to a `N.M.x` branch (where `N` and `M` are integers) it pushes it to NPM as `N.M@next`, so if we have `release-3.2.x`, a merge to that branch will auto-publish `3.2@next`, then, at any point, we can create a tag on `release-3.2.x`, like `v3.2.1` which will publish it to `npm` as `3.2.1`

I think the biggest advantage of this would be that like our CI config, our release config is a pure function of our source repository.

**Comment by cowboyd** [comment]
Also, I love the idea of using `Danger` to enforce changelogs, etc, since it means we could also detect bogus pull requests against the proper branch. Although can we use danger to use a check that actually gates the merge?

**Comment by taras** [comment]
> Although can we use danger to use a check that actually gates the merge?

What do you mean?

**Comment by cowboyd** [comment]
I mean using the GitHub checks API instead of a comment.

**Comment by cowboyd** [comment]
Publish process is now fully automated.
